os: linux
compiler:
  - gcc

env:
  global:
    - LINUX_DIST=xenial

before_script:
  - mkdir build
  - cd build
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir -p external/cmake
      pushd external/cmake
      wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
      chmod +x cmake-*-Linux-x86_64.sh
      ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
      export PATH="${PWD}/bin:$PATH"
      popd
    else
      if ! brew ls --version cmake &>/dev/null; then brew update; brew install cmake; fi
    fi

matrix:
  include:
    - os: linux
      env:
        - TEST="Valgrind"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - valgrind
      script:
        - cmake -DPARALLEL -DCONSISTENT ..
        - make
        - ./../run_valgrind.sh

    - os: linux
      env:
        - TEST="timing + comparison output"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - python
      script:
        - cmake -DPARALLEL -DCONSISTENT ..
        - make
        - cd ../python_scripts
        - python generator.py
        - cd ../build
        - python ../python_scripts/timer.py
        - python ../python_scripts/diff.py

    - os: linux
      env:
        - TEST="Codecov + Tests"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      script:
        - cmake -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON ..
        - make
        - ctest --verbose
        - cd ..
        - export CODECOV_TOKEN="5425c62a-1e9e-4b61-84a4-289806f3c3f0"
        - bash <(curl -s https://codecov.io/bash)

    - os: linux
      env:
        - TEST="cppcheck"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      script:
        - cmake -DENABLE_CPPCHECK=ON ..
        - make
        - make check1 && make check2
